fix: Set ssh_public_key to null (not "") in heat/environment.yaml
Without this change, if the user neglects to set the ssh_public_key
stack parameter, they get an error message that is rather unhelpful to
a new user:

ERROR: The public_key property is required by the nova API version currently used.

By setting it to null (instead of the empty string) in
heat/environment.yaml, they instead get:

ERROR: The Parameter (ssh_public_key) was not provided.

... which is a much more self-explanatory message.